//
//  SVIDef.h
//
//  Created by xiaofan Li on 2017/6/7.
//  Copyright © 2017年 xiaofan Li. All rights reserved.
//

#ifndef SV_DEF_TYPE_H
#define SV_DEF_TYPE_H

typedef enum{
    SVI_EBEAUTY_FILTER= 0,          //美颜
    SVI_SHADOWS_FILTER,
    SVI_CONTRAST_FILTER,
    SVI_SATURATION_FILTER,
    SVI_ACUTANCE_FILTER,
    SVI_BRIGHTNESS_FILTER,
    SVI_WHITENING_FILTER,
    SVI_HIGHLIGHTS_FILTER,
    SVI_GAMMA_FILTER,
    SVI_REDSHIFT_FILTER,
    SVI_GREENSHIFT_FILTER,
    SVI_BLUESHIFT_FILTER,
    SVI_SDREDSHIFT_FILTER,
    SVI_SDGREENSHIFT_FILTER,
    SVI_SDBLUESHIFT_FILTER,
    SVI_HHREDSHIFT_FILTER,
    SVI_HHGREENSHIFT_FILTER,
    SVI_HHBLUESHIFT_FILTER,
    SVI_TEMPERATURE_FILTER,
    SVI_TINT_FILTER
} SVIEFILTERTYPE;


#endif /* SV_DEF_TYPE_H */
